apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-this
  labels:
    app: nginx-this
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-this
  template:
    metadata:
      labels:
        app: nginx-this
    spec:
      containers:
      - name: nginx-this
        image: mhmdlutfi/this:latest
        ports:
        - containerPort: 80
