apiVersion: v1
kind: Pod                 
metadata:           
  name: nginx-this
  labels:
    app: nginx-this
spec:              
  containers:
  - name: nginxthis
    image: mhmdlutfi/this:latest
    ports:
    - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: nginxthis-svc
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
